name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-execute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y ninja cmake

        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          cd src ; cp ../build/* . ; aclocal ; autoconf ; ./configure
          cd .. ; mkdir b ; cd b ; cmake -G Ninja .. ; ninja
          ./socat -V
