name: Testing

on: [push, pull_request]

jobs:
  build-and-execute:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build source code
      run: mkdir b ; cd b ; cp ../build/* . ; aclocal ; cmake .. ; make
    - name: Run build
      run: ./src/socat
