name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-execute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build source code
      run: mkdir b ; cd b ; cp ../build/* . ; aclocal ; cmake .. ; make
    - name: Run build
      run: ./src/socat
